name: Build and Deploy Java app to Azure Spring Cloud

on:
  push:
    branches:
      - new-app

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

# 1. Set up the following secrets in your repository:
#   AZURE_CREDS_FILE
#   CONTRAST_CREDS_FILE
#   DEV_TOKEN

# 2. Change these variables for your configuration:
env:
  JAVA_VERSION: '1.8' # set this to the java version to use
  APPLICATION_NAME: 'springone-petclinic-mark-testing'
  SPRING_CLOUD_SERV_NAME: 'mark-spring-cloud-test'
  DEV_BRANCH: 'new-app'
  ARTIFACT_LOCATION: '/target/*.jar'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 #master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn clean package -DskipTests -Denv=cloud
    - name: Contrast Security Azure Spring Cloud Deployment
      uses: admiralappsec/springone-github-action@main
      id: contrast-deployment
      with:
        application-name: ${{ env.APPLICATION_NAME }}
        spring-cloud-service-name: ${{ env.SPRING_CLOUD_SERV_NAME }}
        application-artifact-location: ${{ env.ARTIFACT_LOCATION }}
        contrast-security-credentials-file: ${{ secrets.CONTRAST_CREDS_FILE }}
        azure-credentials-file: ${{ secrets.AZURE_CREDS_FILE }}
        github-developer-token: ${{ github.token }}
        github-developer-branch: ${{ env.DEV_BRANCH }}
 
  # For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
